package in.bawvpl.Authify.entity;

import lombok.*;
import jakarta.persistence.*;
import java.time.Instant;

@Entity
@Table(name = "payment_orders")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PaymentOrder {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    // Unique Order ID generated by payment provider
    @Column(nullable = false, unique = true)
    private String orderId;

    // User who created the order
    @Column(nullable = false)
    private String userId;

    private double amount;

    // CREATED, PAID, FAILED, EXPIRED etc.
    @Column(nullable = false)
    private String status;

    @Column(name = "createdAt")
    private Instant createdAt;

    @Column(name = "paidAt")
    private Instant paidAt;
}
